export const FETCH_USER = 'FETCH_USER';

export const SEARCH_BARS = 'SEARCH_BARS';
export const LOAD_RESERVED_BARS = 'LOAD_RESERVED_BARS';
export const LOAD_USER_RESERVED_BARS = 'LOAD_USER_RESERVED_BARS';

export const LOADING_STARTS = 'LOADING_STARTS';

export const LOGIN_ERROR = 'LOGIN_ERROR';
